ver: "1.0"
intent_examples:
  off_system: ["выход", "выйди из системы"]
  off_work: ["выключи пк", "заверши работу", "выключи компьютер", "завершить работу"]
  restart_pk: ["перезагрузи пк", "сделай перезагрузку"]
  garbage_cleaning: ["почисти мусор", "очисти мусор"]
  sleep_pk: ["спокойной ночи", "режим сна", "спящий режим"]
  open_provodnic: ["открой проводник"]
  off_provodnic: ["закрой проводник"]




