ver: "1.0"
intent_examples:
  mute: ["включи звук", "выключи звук"]
  volume_pol_zv: ["звук на 50", "звук на половину", "громкость наполовину", "половина"]
  volume_up: ["прибавь немножко громкость", "погромче", "сделай погромче"]
  volume_down: ["убавь немножко громкость", "потише", "сделай потише"]
  volume_max: ["громкость на максимум"]




