ver: "1.0"
intent_examples:
  open_youtube: ["открой ютуб", "открой youtube","YouTube","запусти ютуб"]
  google: ["открой google", "открой гугл"]
  telegram: ["телеграмм", "телеграм", "тг", "открой telegram", "открой телеграмм", "telegram", "Telegram"]
  vk: ["открой вк", "открой века", "открой вконтакте", "открой в контакте", "открой vk"]
  whatsapp: ["watsapp","ватцап","ватсап","открой whatsapp"]
  yandex: ["яндекс","открой яндекс"]
  open_cankuletor: ["открой калькулятор", "запусти калькулятор"]
  phonk: ["фанк", "включи phonk", "фонк", "phonk", "включи фонг", "включи функцию"]
  music: ["слушать музыку", "музыку", "яндекс музыка"]
  music_stol: ["музыка для работы"]
  browser: ["открой браузер", "открой браузер"]
  open_sittings_windows: ["открой настройки виндовс", "запусти настройки виндовс", "открой настройки windows", "запусти настройки windows"]
  open_despecher_zadach: ["открой диспетчер задач", "запусти диспетчер задач"]
  open_menu_pusk: ["открой меню пуск", "запусти меню пуск"]
  open_vkladca: ["открой новую вкладку", "создай новую вкладку"]
  create_papka: ["создай папку", "создай новую папку"]
  zak_okno: ["закрой вкладки", "закрой вкладке", "закрой вкладку"]
  subtitr: ["включи субтитры", "выключи субтитры"]
  youtube_pause: ["поставь на паузу", "воспроизведи", "убери паузу"]
  youtube_kon: ["промотай в конец"]
  youtube_nach: ["промотай в начало"]
  youtube_sled_video: ["следующее видео"]
  youtube_pred_video: ["запусти предыдущее видео", "предыдущее видео", "включи предыдущее видео"]
  youtube_sered: ["промотай на середину"]
  youtube_poln_okno: ["полный экран", "неполный экран", "не полное экран", "не экран", "обычный экран", "обычная экран"]
  youtube_min_proig: ["мини окно", "обычное окно", "mini проигрыватель", "обычная окно"]
  youtube_zak_proig: ["закрой проигрыватель"]
  word_program_open: ["открой ворд", "открой word"]
  create_docx: ["создай новый документ", "создай документ"]
  save_docx: ["сохранить проект", "сохранить документ"]
  cansel_docx: ["закрой документ"]
  cop_all_docx: ["скопируй весь текст", "выделить текст"]
  fat_docx: ["полужирный формат", "пол жирной формат", "пол жирный формат", "жирный формат", "жирной формат", "жирная формат"]
  italics_docx: ["курсивный формат", "формат курсивом"]
  underline_docx: ["формат подчёркивания", "подчеркни"]
  centered_docx: ["выровнять по центру", "выровнять текст по центру"]
  left_docx: ["выровнять по левому краю", "выровнять текст по левому краю"]
  right_docx: ["выровнять по правому краю", "выровнять текст по правому краю"]
  change_language: ["смени язык", "поменяй язык"]




